title: stupidbeardavid
description: 一名算法工程师，人工智能的爱好者，转注于人工智能模型相关的工作，拥有自己维护的深度模型框架.
author: David Lu
avatar: /logo.png
email: sd185115@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: David Lu
  links:
    - https://github.com/luhaofang
    - https://www.zhihu.com/people/david-lu
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
